### ISSUE TITLE
Don't get off mount, if you already on it!

### ISSUE THREAD

**Issue by jinlan** [rheirman/GiddyUpRideAndRoll#9]
My pawn is on a buck, I asked him to do something, it's about 5 hex away, and he dismount to get to it.
If he can directly ride to it, will be much faster.

--------------------------------------------------------------------------------------------

Founded the reason:
Pawn dismount himself right after undrafted. 
So that pawn is dismounted BEFORE I gave him the order.
So. 
Why a pawn dismount himself right after undrafted? It should be uneasy to find a job that request a pawn to instantly dismount himself at the start of the job right?

**Comment by rheirman** [comment]
This is because some jobs cannot be done mounted. Sometimes walking somewhere is part of such a job. The pawn will therefore dismount. In the upcoming release this will be improved: as long as a pawn is moving while doing a job that can't be done mounted, it won't dismount.
